### PR TITLE
Do not add null list response to table state. (master)

### LINKED ISSUE #59: Spamhaus EDROP data adapter issue
There seems to be an issue with the Spamhaus EDROP data adapter. The following log snippet shows three things:

- Timeout while getting the list
- NullPointerException
- Message about a connection leak

Not sure if these are all related to the timeout, but I guess this should be looked at.

```
2017-09-29 08:58:37,777 ERROR: org.graylog.plugins.threatintel.adapters.spamhaus.SpamhausEDROPDataAdapter - Unable to retrieve Spamhaus (E)DROP list <https://w
ww.spamhaus.org/drop/edrop.txt>: 
java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:230) ~[graylog.jar:?]
        at okio.AsyncTimeout.exit(AsyncTimeout.java:285) ~[graylog.jar:?]
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241) ~[graylog.jar:?]
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345) ~[graylog.jar:?]
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217) ~[graylog.jar:?]
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211) ~[graylog.jar:?]
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:187) ~[graylog.jar:?]
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[graylog.jar:?]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[graylog.jar:?]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[graylog.jar:?]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[graylog.jar:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[graylog.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[graylog.jar:?]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[graylog.jar:?]
        at okhttp3.RealCall.execute(RealCall.java:77) ~[graylog.jar:?]
        at org.graylog2.lookup.adapters.dsvhttp.HTTPFileRetriever.fetchFileIfNotModified(HTTPFileRetriever.java:58) ~[graylog.jar:?]
        at org.graylog.plugins.threatintel.adapters.spamhaus.SpamhausEDROPDataAdapter.fetchSubnetsFromEDROPLists(SpamhausEDROPDataAdapter.java:89) ~[?:?]
        at org.graylog.plugins.threatintel.adapters.spamhaus.SpamhausEDROPDataAdapter.doRefresh(SpamhausEDROPDataAdapter.java:71) ~[?:?]
        at org.graylog2.plugin.lookup.LookupDataAdapter.refresh(LookupDataAdapter.java:89) ~[graylog.jar:?]
        at org.graylog2.lookup.LookupDataAdapterRefreshService.lambda$schedule$0(LookupDataAdapterRefreshService.java:142) ~[graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.read(SocketInputStream.java:204) ~[?:1.8.0_131]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_131]
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[?:1.8.0_131]
        at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[?:1.8.0_131]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973) ~[?:1.8.0_131]
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930) ~[?:1.8.0_131]
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[?:1.8.0_131]
        at okio.Okio$2.read(Okio.java:139) ~[graylog.jar:?]
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[graylog.jar:?]
        ... 31 more
2017-09-29 08:58:37,791 ERROR: org.graylog2.plugin.lookup.LookupDataAdapter - Couldn't refresh data adapter <spamhaus-drop/59ca241e0efe211981ef85bf/@53deaa46>
java.lang.NullPointerException: null value in entry: https://www.spamhaus.org/drop/drop.txt=null
        at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34) ~[graylog.jar:?]
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:80) ~[graylog.jar:?]
        at com.google.common.collect.RegularImmutableMap.fromEntries(RegularImmutableMap.java:54) ~[graylog.jar:?]
        at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:430) ~[graylog.jar:?]
        at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:403) ~[graylog.jar:?]
        at org.graylog.plugins.threatintel.adapters.spamhaus.SpamhausEDROPDataAdapter.doRefresh(SpamhausEDROPDataAdapter.java:82) ~[?:?]
        at org.graylog2.plugin.lookup.LookupDataAdapter.refresh(LookupDataAdapter.java:89) ~[graylog.jar:?]
        at org.graylog2.lookup.LookupDataAdapterRefreshService.lambda$schedule$0(LookupDataAdapterRefreshService.java:142) ~[graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
2017-09-29 09:04:27,673 ERROR: org.graylog.plugins.threatintel.adapters.spamhaus.SpamhausEDROPDataAdapter - Unable to retrieve Spamhaus (E)DROP list <https://w
ww.spamhaus.org/drop/edrop.txt>: 
java.io.IOException: Request failed: Bad Gateway
        at org.graylog2.lookup.adapters.dsvhttp.HTTPFileRetriever.fetchFileIfNotModified(HTTPFileRetriever.java:72) ~[graylog.jar:?]
        at org.graylog.plugins.threatintel.adapters.spamhaus.SpamhausEDROPDataAdapter.fetchSubnetsFromEDROPLists(SpamhausEDROPDataAdapter.java:89) ~[?:?]
        at org.graylog.plugins.threatintel.adapters.spamhaus.SpamhausEDROPDataAdapter.doRefresh(SpamhausEDROPDataAdapter.java:71) ~[?:?]
        at org.graylog2.plugin.lookup.LookupDataAdapter.refresh(LookupDataAdapter.java:89) ~[graylog.jar:?]
        at org.graylog2.lookup.LookupDataAdapterRefreshService.lambda$schedule$0(LookupDataAdapterRefreshService.java:142) ~[graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
2017-09-29 09:04:27,674 ERROR: org.graylog2.plugin.lookup.LookupDataAdapter - Couldn't refresh data adapter <spamhaus-drop/59ca241e0efe211981ef85bf/@53deaa46>
java.lang.NullPointerException: null value in entry: https://www.spamhaus.org/drop/drop.txt=null
        at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34) ~[graylog.jar:?]
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:80) ~[graylog.jar:?]
        at com.google.common.collect.RegularImmutableMap.fromEntries(RegularImmutableMap.java:54) ~[graylog.jar:?]
        at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:430) ~[graylog.jar:?]
        at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:403) ~[graylog.jar:?]
        at org.graylog.plugins.threatintel.adapters.spamhaus.SpamhausEDROPDataAdapter.doRefresh(SpamhausEDROPDataAdapter.java:82) ~[?:?]
        at org.graylog2.plugin.lookup.LookupDataAdapter.refresh(LookupDataAdapter.java:89) ~[graylog.jar:?]
        at org.graylog2.lookup.LookupDataAdapterRefreshService.lambda$schedule$0(LookupDataAdapterRefreshService.java:142) ~[graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
2017-09-29 09:06:26,341 WARN : okhttp3.OkHttpClient - A connection to https://www.spamhaus.org/ was leaked. Did you forget to close a response body? To see whe
re this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```

### PR DESCRIPTION
**Pull request by dennisoelkers**
This change makes sure that the fetched response for a blocklist not null before adding it to the map builder and adds tests to verify the behavior.

Fixes #59.

### CODE REVIEW

File: src/main/java/org/graylog/plugins/threatintel/adapters/spamhaus/SpamhausEDROPDataAdapter.java [hunk 1]
```diff
@@ -59,7 +59,10 @@ public SpamhausEDROPDataAdapter(@Assisted("id") String id,
     public void doStart() throws Exception {
         final ImmutableMap.Builder<String, Map<SubnetUtils.SubnetInfo, String>> builder = ImmutableMap.builder();
         for (String list : lists) {
-            builder.put(list, fetchSubnetsFromEDROPLists(list));
+            final Map<SubnetUtils.SubnetInfo, String> subnetMap = fetchSubnetsFromEDROPLists(list);
+            if (subnetMap != null) {
```
Comment (joschi) [inline src/main/java/org/graylog/plugins/threatintel/adapters/spamhaus/SpamhausEDROPDataAdapter.java]: Doesn't the same problem exist in the `doRefresh()` method (line 74)?

Comment (joschi) [reply src/main/java/org/graylog/plugins/threatintel/adapters/spamhaus/SpamhausEDROPDataAdapter.java]: Would it solve the problem if `fetchSubnetsFromEDROPLists()` returned an empty map instead of `null` when nothing changed?

Comment (dennisoelkers) [reply src/main/java/org/graylog/plugins/threatintel/adapters/spamhaus/SpamhausEDROPDataAdapter.java]: How do we differentiate between the retrieval of an empty and a non-changing list?

Comment (dennisoelkers) [reply src/main/java/org/graylog/plugins/threatintel/adapters/spamhaus/SpamhausEDROPDataAdapter.java]: The `doRefresh()` does not suffer from the same problem, because it is using a `HashMap` instead of an `ImmutableMap.Builder`. In that part of the code it is iterating over the null entries afterwards to populate them with the last retrieved versions of them.

Comment (dennisoelkers) [reply src/main/java/org/graylog/plugins/threatintel/adapters/spamhaus/SpamhausEDROPDataAdapter.java]: Yes, if we return `null`, we do not update the list and use the version of the list that was retrieved successfully last time. If we would return an empty map, it would replace the list with an empty one. It is an edge case that one of the two lists might be emptied, but it is possible.
