### PR TITLE
Handle absent OTX API key in ThreatIntelPluginConfiguration

### LINKED ISSUE #53: Unable to change Threat Intelligence configuration
When trying to change the configuration on the System -> Configuations page, the following exception is thrown:
```text
2017-09-26 15:39:05,896 ERROR: org.graylog2.rest.resources.system.ClusterConfigResource - Couldn't parse cluster configuration "org.graylog.plugins.threatintel.ThreatIntelPluginConfiguration".
com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of org.graylog.plugins.threatintel.ThreatIntelPluginConfiguration, problem: Null otxApiKey
 at [Source: org.glassfish.jersey.message.internal.EntityInputStream@3018e231; line: 1, column: 95]
	[...]
Caused by: java.lang.NullPointerException: Null otxApiKey
	at org.graylog.plugins.threatintel.AutoValue_ThreatIntelPluginConfiguration$Builder.otxApiKey(AutoValue_ThreatIntelPluginConfiguration.java:119) ~[classes/:?]
	at org.graylog.plugins.threatintel.ThreatIntelPluginConfiguration.create(ThreatIntelPluginConfiguration.java:41) ~[classes/:?]
	[...]
```

### PR DESCRIPTION
**Pull request by joschi**
Fixes #53

### CODE REVIEW

File: src/main/java/org/graylog/plugins/threatintel/ThreatIntelPluginConfiguration.java [hunk 1]
```diff
@@ -19,7 +19,8 @@
     public abstract boolean otxEnabled();
 
     @JsonProperty("otx_api_key")
-    public abstract Optional<String> otxApiKey();
+    @Nullable
+    public abstract String otxApiKey();
```
Comment (bernd) [inline src/main/java/org/graylog/plugins/threatintel/ThreatIntelPluginConfiguration.java]: Wouldn't this be enough so we can keep the nice properties of `java.util.Optional`?

```diff
diff --git src/main/java/org/graylog/plugins/threatintel/ThreatIntelPluginConfiguration.java src/main/java/org/graylog/plugins/threatintel/ThreatIntelPluginConfiguration.java
index 130fa5d..9b983fa 100644
--- src/main/java/org/graylog/plugins/threatintel/ThreatIntelPluginConfiguration.java
+++ src/main/java/org/graylog/plugins/threatintel/ThreatIntelPluginConfiguration.java
@@ -38,7 +37,7 @@ public abstract class ThreatIntelPluginConfiguration {
                                                         @JsonProperty("abusech_ransom_enabled") boolean abusechRansomEnabled) {
         return builder()
                 .otxEnabled(otxEnabled)
-                .otxApiKey(otxApiKey)
+                .otxApiKey(Optional.ofNullable(otxApiKey))
                 .torEnabled(torEnabled)
                 .spamhausEnabled(spamhausEnabled)
                 .abusechRansomEnabled(abusechRansomEnabled)
@@ -62,7 +61,7 @@ public abstract class ThreatIntelPluginConfiguration {
     public static abstract class Builder {
         public abstract Builder otxEnabled(boolean otxEnabled);
 
-        public abstract Builder otxApiKey(String otxApiKey);
+        public abstract Builder otxApiKey(Optional<String> otxApiKey);
 
         public abstract Builder torEnabled(boolean torEnabled);
```

Comment (joschi) [reply src/main/java/org/graylog/plugins/threatintel/ThreatIntelPluginConfiguration.java]: Maybe, but `Optional<T>` is pretty useless in this case anyway (check the usages of `ThreatIntelPluginConfiguration#otxApiKey()`).
In other words, getting rid of the `Optional<T>` meant having less code.

Comment (bernd) [reply src/main/java/org/graylog/plugins/threatintel/ThreatIntelPluginConfiguration.java]: I wouldn't call it useless, but fair enough.
