### PR TITLE
Fix bug that always causes a false Tor Exit Node response

### LINKED ISSUE #115: tor_lookup pipeline function returns always false
## Expected Behavior

I tested the pipeline function `tor_lookup` with several tor exit node's addressess, but all I got was `{"threat_indicated":false}` response. Does it work for anyone?

## Current Behavior

Only negative response `{"threat_indicated":false}` is returned as a result of tor lookup, there is no error message in the log.

## Steps to Reproduce (for bugs)

I tested the lookup function with the following IP addressess where I would expect positive tor lookup result:

obrazek

but I got false in case of all of these IP addressess. 

Pipeline function used:

```
rule "add_tor_lookup"
when 
    has_field("source_address")
then
    let tor_lookup = tor_lookup(to_string($message.source_address));
    set_field("tor_lookup", tor_lookup);
end 
```

Does the (now built-in) tor lookup plugin work for someone? Maybe I'm doing something wrong?

## Your Environment

* Graylog Version: 2.4.1
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

### PR DESCRIPTION
**Pull request by danotorrey**
Fixes #115 (`tor_lookup` pipeline function always returns a false `threat_indicated` response).

The was previously attempting to parse a boolean response from the Tor Exit Node data adaptor/lookup table (but the table returns the Tor node ID if found). Now, the code correctly return false for a blank/null Tor node ID, and true when an ID of any length is returned.

### CODE REVIEW

**Comment by danotorrey** [comment]
My testing passed. Ready for review.

File: src/main/java/org/graylog/plugins/threatintel/functions/tor/TorExitNodeLookupFunction.java [hunk 1]
```diff
@@ -42,12 +43,11 @@ public GenericLookupResult evaluate(FunctionArgs args, EvaluationContext context
...
         if (lookupResult != null && !lookupResult.isEmpty()) {
+
+            // If not a String, then fall through to false at the end of the method.
             final Object value = lookupResult.singleValue();
-            if (value instanceof Boolean) {
-                return (Boolean) value ? GenericLookupResult.TRUE : GenericLookupResult.FALSE;
-            }
             if (value instanceof String) {
-                return Boolean.valueOf((String) value) ? GenericLookupResult.TRUE : GenericLookupResult.FALSE;
+                return Strings.isNotBlank((String) value) ? GenericLookupResult.TRUE : GenericLookupResult.FALSE;
```
Comment (bernd) [inline src/main/java/org/graylog/plugins/threatintel/functions/tor/TorExitNodeLookupFunction.java]: We usually use `com.google.common.base.Strings.isNullOrEmpty` in such cases. I think this is a better choice here so we don't pull in a class from the specific logger implementation.

**Comment by danotorrey** [comment]
@bernd Great catch! Fixed.
